// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! Shader composition at build time (RFC-001 "Decisions (2026-10-09)",
//! GUP-406).
//!
//! naga_oil composes every WGSL file in `src/shaders` once, here:
//!
//! - **library modules** (files with `#define_import_path`) are flattened
//!   to plain WGSL whose items carry `gup_wgsl::flat_name`s, and become
//!   `WgslModule` statics (`gup::scale::linear` → `SCALE_LINEAR`);
//! - **top-level shaders** (the others) are flattened completely and
//!   become `<STEM>_SHADER` constants.
//!
//! Both land in `$OUT_DIR/shaders.rs`, which `src/shader/mod.rs` includes.
//! A composition error fails the build with naga_oil's report, which names
//! the source file and line.

use gup_wgsl::compose::{Error, Library, read_dir};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=src/shaders");
    if let Err(e) = generate() {
        eprintln!("{e}");
        // `cargo build` prints the report above under "--- stderr".
        println!(
            "cargo::error=gup-core's WGSL failed to compose at build time ({}); \
             naga_oil's report follows under stderr",
            e.module
        );
        std::process::exit(1);
    }
}

/// `gup::scale::linear` → `SCALE_LINEAR`.
fn static_name(import_path: &str) -> String {
    import_path
        .strip_prefix("gup::")
        .unwrap_or(import_path)
        .replace("::", "_")
        .to_uppercase()
}

fn generate() -> Result<(), Error> {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("set by cargo"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("set by cargo"));
    let wgsl_dir = out.join("wgsl");
    let write = |name: &str, text: &str| {
        std::fs::write(wgsl_dir.join(name), text)
            .map_err(|e| Error::new(name, format!("writing {}: {e}", out.display())))
    };
    std::fs::create_dir_all(&wgsl_dir)
        .map_err(|e| Error::new("OUT_DIR", format!("{}: {e}", wgsl_dir.display())))?;

    let dir = read_dir(&manifest.join("src/shaders"), "src/shaders")?;
    let mut lib = Library::new(&dir.modules)?;
    let mut rs = String::from("// Generated by gup-core's build.rs; do not edit.\n\n");
    let include =
        |file: &str| format!("include_str!(concat!(env!(\"OUT_DIR\"), \"/wgsl/{file}\"))");

    for m in lib.modules() {
        let file = format!("{}.wgsl", m.import_path.replace("::", "_"));
        write(&file, &m.wgsl)?;
        let imports: Vec<String> = m
            .imports
            .iter()
            .map(|p| format!("&{}", static_name(p)))
            .collect();
        let _ = writeln!(
            rs,
            "/// `{path}`, flattened at build time from `{src}`.\n\
             pub static {name}: WgslModule = WgslModule {{\n    \
             import_path: {path:?},\n    \
             wgsl: {text},\n    \
             imports: &[{imports}],\n}};\n",
            path = m.import_path,
            src = m.file,
            name = static_name(&m.import_path),
            text = include(&file),
            imports = imports.join(", "),
        );
    }
    let all: Vec<String> = lib
        .modules()
        .iter()
        .map(|m| format!("&{}", static_name(&m.import_path)))
        .collect();
    let _ = writeln!(
        rs,
        "/// Every library module, dependencies first.\n\
         #[cfg(test)]\n\
         pub(crate) static BUILTIN_MODULES: &[&WgslModule] = &[{}];\n",
        all.join(", ")
    );

    for shader in &dir.shaders {
        let text = lib.flatten_shader(&shader.file, &shader.text)?;
        let stem = Path::new(&shader.file)
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_default();
        let file = format!("{stem}.wgsl");
        write(&file, &text)?;
        let _ = writeln!(
            rs,
            "/// The top-level shader `{src}`, flattened at build time.\n\
             pub(crate) const {name}_SHADER: &str = {text};\n",
            src = shader.file,
            name = stem.to_uppercase(),
            text = include(&file),
        );
    }
    std::fs::write(out.join("shaders.rs"), rs)
        .map_err(|e| Error::new("shaders.rs", format!("writing {}: {e}", out.display())))
}
