// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! Validates that WGSL generated by the transpilation prototype
//! compiles correctly with wgpu/naga.
//!
//! These tests exercise the GPU shader compiler to ensure the
//! transpiler produces valid WGSL output.

/// Validate that a WGSL string compiles with wgpu/naga.
async fn validate_wgsl_compiles(label: &str, wgsl: &str) {
    let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
        backends: wgpu::Backends::all(),
        ..Default::default()
    });
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions::default())
        .await
        .expect("No GPU adapter available");
    let (device, _queue) = adapter
        .request_device(&wgpu::DeviceDescriptor::default())
        .await
        .expect("Failed to create device");

    // Wrap in a compute entry point for validation
    let validation_wgsl = format!(
        "{wgsl}\n\n@compute @workgroup_size(1)\nfn main() {{\n    // validation entry point\n}}"
    );

    let _module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some(label),
        source: wgpu::ShaderSource::Wgsl(std::borrow::Cow::Borrowed(&validation_wgsl)),
    });
}

#[tokio::test]
async fn transpiled_identity_function_compiles() {
    // Represents output of transpiling: fn identity(value: f32) -> f32 { return value; }
    let wgsl = "fn identity(value: f32) -> f32 {\n    return value;\n}\n";
    validate_wgsl_compiles("identity", wgsl).await;
}

#[tokio::test]
async fn transpiled_arithmetic_compiles() {
    // Represents output of transpiling:
    // fn transform(value: f32, scale: f32, offset: f32) -> f32 {
    //     return value * scale + offset;
    // }
    let wgsl = "\
struct TransformUniforms {
    scale: f32,
    offset: f32,
}

fn transform(value: f32, uniforms: TransformUniforms) -> f32 {
    return value * uniforms.scale + uniforms.offset;
}
";
    validate_wgsl_compiles("arithmetic", wgsl).await;
}

#[tokio::test]
async fn transpiled_let_bindings_compile() {
    // Represents output of transpiling a function with let bindings
    let wgsl = "\
fn normalize(value: f32) -> f32 {
    let shifted = value - 0.5;
    let scaled = shifted * 2.0;
    let clamped = clamp(scaled, 0.0, 1.0);
    return clamped;
}
";
    validate_wgsl_compiles("let_bindings", wgsl).await;
}

#[tokio::test]
async fn transpiled_type_cast_compiles() {
    // Represents output of transpiling: idx as f32 → f32(idx)
    let wgsl = "\
fn to_float(idx: i32) -> f32 {
    return f32(idx);
}
";
    validate_wgsl_compiles("type_cast", wgsl).await;
}

#[tokio::test]
async fn transpiled_vec_constructor_compiles() {
    // Represents output of transpiling: Vec2(x, 0.0) → vec2<f32>(x, 0.0)
    let wgsl = "\
fn make_pos(x: f32) -> vec2<f32> {
    return vec2<f32>(x, 0.0);
}
";
    validate_wgsl_compiles("vec_constructor", wgsl).await;
}

#[tokio::test]
async fn transpiled_builtin_functions_compile() {
    // Represents output of transpiling methods to WGSL builtins
    let wgsl = "\
fn process(value: f32) -> f32 {
    let a = abs(value);
    let s = sqrt(a);
    let c = clamp(s, 0.0, 1.0);
    return c;
}
";
    validate_wgsl_compiles("builtins", wgsl).await;
}

#[tokio::test]
async fn transpiled_complex_expression_compiles() {
    // Represents a more complex transpilation output
    let wgsl = "\
struct LinearScaleUniforms {
    domain_min: f32,
    domain_max: f32,
    range_min: f32,
    range_max: f32,
}

fn linear_scale(value: f32, uniforms: LinearScaleUniforms) -> f32 {
    let normalised = (value - uniforms.domain_min) / (uniforms.domain_max - uniforms.domain_min);
    return uniforms.range_min + normalised * (uniforms.range_max - uniforms.range_min);
}
";
    validate_wgsl_compiles("complex_expression", wgsl).await;
}

#[tokio::test]
async fn transpiled_unary_and_comparison_compiles() {
    // Tests unary negation and comparison operators
    let wgsl = "\
fn negate_if_positive(value: f32) -> f32 {
    if (value > 0.0) {
        return -value;
    }
    return value;
}
";
    validate_wgsl_compiles("unary_comparison", wgsl).await;
}
