// gup glue: Circle {x: f32rel→gup::scale::linear::map_rel, y: f32→gup::scale::log::map, radius: const f32, fill: u32→gup::color::categorical::map} with nulls
// Generated by gup-core's glue emitter; do not edit.
#import gup::view::{View}
#import gup::marks::circle as circle
#import gup::scale::linear as linear
#import gup::scale::log as log
#import gup::color::categorical as categorical

struct Encodings {
    x: linear::Params,
    y: log::Params,
    radius: f32,
    radius_pad_a: u32,
    radius_pad_b: u32,
    radius_pad_c: u32,
    fill: categorical::Params,
}

struct Chunk {
    row_base: u32,
    x_base: f32,
}

@group(0) @binding(0) var<uniform> u_view: View;
@group(1) @binding(0) var<uniform> enc: Encodings;
@group(2) @binding(0) var<uniform> chunk: Chunk;
@group(2) @binding(1) var<storage, read> validity: array<u32>;

struct Columns {
    @location(0) x: f32,
    @location(1) y: f32,
    @location(2) fill: u32,
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32, col: Columns) -> circle::Varyings {
    let valid_group = (instance_index / 32u) * 2u;
    let valid_bit = instance_index % 32u;
    var m: circle::CircleIn;
    m.x = linear::map_rel(col.x, chunk.x_base, enc.x);
    m.y = log::map(col.y, enc.y);
    m.radius = enc.radius;
    m.fill = categorical::map(col.fill, enc.fill);
    var out = circle::vertex(m, vertex_index, chunk.row_base + instance_index, u_view);
    let drawn = ((validity[valid_group + 0u] & validity[valid_group + 1u]) >> valid_bit) & 1u;
    out.clip = select(vec4<f32>(2.0, 2.0, 2.0, 1.0), out.clip, drawn == 1u);
    return out;
}

@fragment
fn fs_main(v: circle::Varyings) -> @location(0) vec4<f32> {
    return circle::shade(v);
}
