// gup glue: Circle {x: f32rel→gup::scale::linear::map_rel, y: f32→gup::scale::log::map, radius: const f32, fill: f32→gup::color::sequential::map(lut)}
// Generated by gup-core's glue emitter; do not edit.
#import gup::view::{View}
#import gup::marks::circle as circle
#import gup::scale::linear as linear
#import gup::scale::log as log
#import gup::color::sequential as sequential

struct Encodings {
    x: linear::Params,
    y: log::Params,
    radius: f32,
    radius_pad_a: u32,
    radius_pad_b: u32,
    radius_pad_c: u32,
    fill: sequential::Params,
}

struct Chunk {
    row_base: u32,
    x_base: f32,
}

@group(0) @binding(0) var<uniform> u_view: View;
@group(1) @binding(0) var<uniform> enc: Encodings;
@group(1) @binding(1) var fill_lut: texture_2d<f32>;
@group(1) @binding(2) var fill_smp: sampler;
@group(2) @binding(0) var<uniform> chunk: Chunk;

struct Columns {
    @location(0) x: f32,
    @location(1) y: f32,
    @location(2) fill: f32,
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32, col: Columns) -> circle::Varyings {
    var m: circle::CircleIn;
    m.x = linear::map_rel(col.x, chunk.x_base, enc.x);
    m.y = log::map(col.y, enc.y);
    m.radius = enc.radius;
    m.fill = sequential::map(col.fill, enc.fill, fill_lut, fill_smp);
    return circle::vertex(m, vertex_index, chunk.row_base + instance_index, u_view);
}

@fragment
fn fs_main(v: circle::Varyings) -> @location(0) vec4<f32> {
    return circle::shade(v);
}
