// gup glue: Circle {x: f32rel→gup::scale::linear::map_rel, y: f32→gup::scale::log::map, radius: const f32, fill: f32→gup::color::sequential::map(lut)}
// Generated by gup-core's glue emitter; do not edit.
// #import gup::view::{View}
// #import gup::marks::circle as circle
// #import gup::scale::linear as linear
// #import gup::scale::log as log
// #import gup::color::sequential as sequential

struct Encodings {
    x: gup_scale_linear_Params,
    y: gup_scale_log_Params,
    radius: f32,
    radius_pad_a: u32,
    radius_pad_b: u32,
    radius_pad_c: u32,
    fill: gup_color_sequential_Params,
}

struct Chunk {
    row_base: u32,
    x_base: f32,
}

@group(0) @binding(0) var<uniform> u_view: gup_view_View;
@group(1) @binding(0) var<uniform> enc: Encodings;
@group(1) @binding(1) var fill_lut: texture_2d<f32>;
@group(1) @binding(2) var fill_smp: sampler;
@group(2) @binding(0) var<uniform> chunk: Chunk;

struct Columns {
    @location(0) x: f32,
    @location(1) y: f32,
    @location(2) fill: f32,
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32, col: Columns) -> gup_marks_circle_Varyings {
    var m: gup_marks_circle_CircleIn;
    m.x = gup_scale_linear_map_rel(col.x, chunk.x_base, enc.x);
    m.y = gup_scale_log_map(col.y, enc.y);
    m.radius = enc.radius;
    m.fill = gup_color_sequential_map(col.fill, enc.fill, fill_lut, fill_smp);
    return gup_marks_circle_vertex(m, vertex_index, chunk.row_base + instance_index, u_view);
}

@fragment
fn fs_main(v: gup_marks_circle_Varyings) -> @location(0) vec4<f32> {
    return gup_marks_circle_shade(v);
}

// gup::view (flattened at build time)
struct gup_view_View {
    size: vec2<f32>,
    dpr: f32,
    padding: f32,
}

fn gup_view_px_to_clip(p: vec2<f32>, view: gup_view_View) -> vec4<f32> {
    let ndc = vec2<f32>((((p.x / view.size.x) * 2f) - 1f), (1f - ((p.y / view.size.y) * 2f)));
    return vec4<f32>(ndc, 0f, 1f);
}

// gup::marks::circle (flattened at build time)
struct gup_marks_circle_CircleIn {
    x: f32,
    y: f32,
    radius: f32,
    fill: vec4<f32>,
}

struct gup_marks_circle_Varyings {
    @builtin(position) clip: vec4<f32>,
    @location(0) local: vec2<f32>,
    @location(1) radius: f32,
    @location(2) fill: vec4<f32>,
    @location(3) @interpolate(flat) row: u32,
}

fn gup_marks_circle_corner(vertex_index: u32) -> vec2<f32> {
    var corners: array<vec2<f32>, 6> = array<vec2<f32>, 6>(vec2<f32>(-1f, -1f), vec2<f32>(1f, -1f), vec2<f32>(-1f, 1f), vec2<f32>(-1f, 1f), vec2<f32>(1f, -1f), vec2<f32>(1f, 1f));

    let _e10 = corners[vertex_index];
    return _e10;
}

fn gup_marks_circle_vertex(m: gup_marks_circle_CircleIn, vertex_index_1: u32, row: u32, view_1: gup_view_View) -> gup_marks_circle_Varyings {
    var out: gup_marks_circle_Varyings;

    let half = (m.radius + (1f / view_1.dpr));
    let _e8 = gup_marks_circle_corner(vertex_index_1);
    let offset = (_e8 * half);
    let _e16 = gup_view_px_to_clip((vec2<f32>(m.x, m.y) + offset), view_1);
    out.clip = _e16;
    out.local = (offset * view_1.dpr);
    out.radius = (m.radius * view_1.dpr);
    out.fill = m.fill;
    out.row = row;
    let _e28 = out;
    return _e28;
}

fn gup_marks_circle_shade(v: gup_marks_circle_Varyings) -> vec4<f32> {
    let distance = (length(v.local) - v.radius);
    let coverage = clamp((0.5f - distance), 0f, 1f);
    let alpha = (v.fill.w * coverage);
    if (alpha <= 0f) {
        discard;
    }
    return vec4<f32>((v.fill.xyz * alpha), alpha);
}

// gup::scale::linear (flattened at build time)
struct gup_scale_linear_Params {
    k: f32,
    range_start: f32,
    pad_a: u32,
    pad_b: u32,
}

fn gup_scale_linear_map_rel(v: f32, base: f32, p: gup_scale_linear_Params) -> f32 {
    return (p.range_start + ((v + base) * p.k));
}

// gup::scale::log (flattened at build time)
struct gup_scale_log_Params {
    log_lo: f32,
    inv_log_span: f32,
    range_start: f32,
    r_span: f32,
}

fn gup_scale_log_map(v: f32, p: gup_scale_log_Params) -> f32 {
    return (p.range_start + (((log2(v) - p.log_lo) * p.inv_log_span) * p.r_span));
}

// gup::color::sequential (flattened at build time)
struct gup_color_sequential_Params {
    lo: f32,
    inv_span: f32,
    reverse: u32,
    padding: u32,
}

fn gup_color_sequential_map(v: f32, p: gup_color_sequential_Params, lut: texture_2d<f32>, smp: sampler) -> vec4<f32> {
    var t: f32;

    t = clamp(((v - p.lo) * p.inv_span), 0f, 1f);
    if (p.reverse != 0u) {
        let _e13 = t;
        t = (1f - _e13);
    }
    let _e17 = textureDimensions(lut);
    let n = f32(_e17.x);
    let _e20 = t;
    let u = (((_e20 * (n - 1f)) + 0.5f) / n);
    let _e31 = textureSampleLevel(lut, smp, vec2<f32>(u, 0.5f), 0f);
    return _e31;
}
