// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! Shader composition (RFC-001 §6): WGSL library modules flattened at
//! build time, plus the typed glue emitter in [`glue`].
//!
//! `build.rs` runs naga_oil over `src/shaders` once, at build time, on
//! every target (RFC-001 "Decisions (2026-10-09)", GUP-406). Library
//! modules (marks, scales, palettes, the view transform) become plain WGSL
//! whose items have flat names (`gup::scale::linear::map_rel` →
//! `gup_scale_linear_map_rel`), as the [`WgslModule`] statics below; the
//! hand-authored guide shaders are flattened completely. At run time the
//! glue emitter prints one top-level module per `(mark, encoding
//! signature)`, [`link`] joins it to the flattened modules it imports, and
//! wgpu gets the result as WGSL: one path on native and wasm, with no naga
//! or naga_oil in the binary. **Gup never edits authored WGSL as text.**

pub(crate) mod glue;

use crate::error::{Error, Result};
pub use gup_wgsl::WgslModule;

// The library statics (`VIEW`, `SCALE_LINEAR`, …, `MARKS_CIRCLE`) and the
// guide shaders (`RULE_SHADER`, …), generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/shaders.rs"));

/// Link a generated top-level module against the flattened library
/// modules it imports (see [`gup_wgsl::link`]).
pub(crate) fn link(label: &str, source: &str, modules: &[&'static WgslModule]) -> Result<String> {
    gup_wgsl::link(label, source, modules).map_err(|e| Error::Compose {
        module: label.to_string(),
        report: e.to_string(),
    })
}

/// Byte layout of a uniform struct in a generated module.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct StructLayout {
    /// Total size in bytes (the struct's span).
    pub span: u32,
    /// `(member name, byte offset)` in declaration order.
    pub members: Vec<(String, u32)>,
}

impl StructLayout {
    /// The offset of member `name`.
    pub(crate) fn offset(&self, name: &str) -> Option<u32> {
        self.members
            .iter()
            .find(|(n, _)| n == name)
            .map(|&(_, o)| o)
    }
}

/// Test helpers: naga (a dev-dependency only) re-parses linked WGSL.
#[cfg(test)]
pub(crate) mod testing {
    use super::StructLayout;

    /// Parse and validate standalone WGSL, panicking with naga's report.
    pub(crate) fn parse(label: &str, wgsl: &str) -> naga::Module {
        gup_wgsl::compose::parse_wgsl(label, wgsl).unwrap_or_else(|e| panic!("{e}\n{wgsl}"))
    }

    /// naga's layout of struct `name` in `module`.
    pub(crate) fn struct_layout(module: &naga::Module, name: &str) -> Option<StructLayout> {
        gup_wgsl::compose::struct_layouts(module)
            .into_iter()
            .find(|(n, _)| n == name)
            .map(|(_, l)| StructLayout {
                span: l.span,
                members: l.members,
            })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_library_module_is_standalone_wgsl() {
        for m in BUILTIN_MODULES {
            let linked =
                link(m.import_path, &format!("#import {}\n", m.import_path), &[m]).unwrap();
            assert!(!linked.contains("\n#"), "{linked}");
            testing::parse(m.import_path, &linked);
        }
    }

    #[test]
    fn guide_shaders_are_complete_wgsl() {
        for (name, source) in [
            ("rule", RULE_SHADER),
            ("rect", RECT_SHADER),
            ("gradient", GRADIENT_SHADER),
        ] {
            let module = testing::parse(name, source);
            assert_eq!(module.entry_points.len(), 2, "{name}");
        }
    }

    #[test]
    fn link_errors_name_the_generated_line() {
        let err = link(
            "broken_glue",
            "#import gup::scale::linear as linear\n\
             fn f() -> f32 { return linear::map_relx(1.0, 2.0); }\n",
            &[&SCALE_LINEAR],
        )
        .expect_err("unknown item must fail");
        let text = err.to_string();
        assert!(
            text.contains("broken_glue:2: `gup::scale::linear` has no item `map_relx`"),
            "{text}"
        );
    }
}
