// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! Integration showcase demonstrating various ways to integrate external visualization
//! types with Gup's Mixable trait ecosystem.
//!
//! This example shows:
//! - Using the derive macro for automatic Mixable implementation
//! - Wrapping external data types with integration helpers
//! - Creating and using custom plugins
//! - Composing integrated types with native Gup visualizations

use gup::integration::*;
use gup::plugins::*;
use gup::{GupError, GupResult, Mixable, MixableExt, RenderContext};
use std::any::{Any, TypeId};

// Example 1: Using derive macro for automatic Mixable implementation
// Note: This would require importing the derive macro with `use gup_macros::Mixable;`
// but for this example we'll show what the generated code would look like

/// A simple scatter plot that can be automatically made Mixable
#[derive(Debug, Clone)]
// #[derive(Mixable)]  // Would be enabled with gup_macros::Mixable
// #[mixable(render_type = "points")]
pub struct AutoScatterPlot {
    // #[mixable(vertex_data)]
    pub points: Vec<[f32; 2]>,
    // #[mixable(uniform_data, binding = 0)]
    pub color: [f32; 4],
    // #[mixable(uniform_data, binding = 1)]
    pub size: f32,
}

// Manual implementation for demonstration (would be auto-generated by derive macro)
impl Mixable for AutoScatterPlot {
    type Output = ();

    fn render(&mut self, context: &mut RenderContext) -> GupResult<()> {
        if self.points.is_empty() {
            return Ok(());
        }

        // TODO: In a real implementation, this would set up uniforms and render with proper GPU pipelines
        // For now, just return Ok to demonstrate the API
        let _ = context; // Suppress unused parameter warning
        Ok(())
    }

    fn is_valid(&self) -> bool {
        !self.points.is_empty()
    }

    fn description(&self) -> String {
        format!("AutoScatterPlot({} points)", self.points.len())
    }
}

impl AutoScatterPlot {
    pub fn new(points: Vec<[f32; 2]>, color: [f32; 4], size: f32) -> Self {
        Self {
            points,
            color,
            size,
        }
    }
}

// Example 2: External library types that need integration

/// Simulated external charting library data
#[derive(Debug)]
pub struct ExternalChartLibrary {
    pub chart_data: ExternalChart,
}

#[derive(Debug)]
pub struct ExternalChart {
    pub data_points: Vec<(f64, f64)>, // Note: f64 instead of f32
    pub chart_type: ExternalChartType,
    pub style: ChartStyle,
}

#[derive(Debug)]
pub enum ExternalChartType {
    Line,
    Scatter,
    Bar,
    Area,
}

#[derive(Debug)]
pub struct ChartStyle {
    pub color: (u8, u8, u8), // RGB color
    pub thickness: u32,
}

impl ExternalChart {
    pub fn new_scatter(data: Vec<(f64, f64)>, color: (u8, u8, u8)) -> Self {
        Self {
            data_points: data,
            chart_type: ExternalChartType::Scatter,
            style: ChartStyle {
                color,
                thickness: 2,
            },
        }
    }

    pub fn new_line(data: Vec<(f64, f64)>, color: (u8, u8, u8), thickness: u32) -> Self {
        Self {
            data_points: data,
            chart_type: ExternalChartType::Line,
            style: ChartStyle { color, thickness },
        }
    }
}

// Example 3: Plugin for the external chart library
#[derive(Debug)]
pub struct ExternalChartPlugin;

impl MixablePlugin for ExternalChartPlugin {
    fn name(&self) -> &str {
        "external_chart_library"
    }

    fn version(&self) -> &str {
        "1.2.0"
    }

    fn can_handle(&self, type_id: TypeId) -> bool {
        type_id == TypeId::of::<ExternalChart>()
    }

    fn create_mixable(&self, object: Box<dyn Any + Send + Sync>) -> Box<dyn Mixable<Output = ()>> {
        if let Ok(chart) = object.downcast::<ExternalChart>() {
            // Convert the external chart to a Mixable wrapper
            let wrapped = wrap_point_data(*chart, |chart| {
                chart.data_points
                    .iter()
                    .map(|&(x, y)| [x as f32, y as f32]) // Convert f64 to f32
                    .collect()
            });
            Box::new(wrapped)
        } else {
            panic!("ExternalChartPlugin received unexpected type");
        }
    }

    fn validate(&self) -> Result<(), String> {
        // In a real plugin, you might check for external library availability
        Ok(())
    }

    fn metadata(&self) -> PluginMetadata {
        PluginMetadata {
            name: self.name().to_string(),
            version: self.version().to_string(),
            description: "Integration plugin for External Chart Library".to_string(),
            author: "Gup Integration Team".to_string(),
            supported_types: vec!["ExternalChart".to_string()],
        }
    }
}

// Example 4: Data format conversion utilities demonstration

/// CSV data that needs to be converted to visualization format
#[derive(Debug)]
pub struct CsvData {
    pub headers: Vec<String>,
    pub rows: Vec<Vec<String>>,
}

impl Default for CsvData {
    fn default() -> Self {
        Self::new()
    }
}

impl CsvData {
    pub fn new() -> Self {
        Self {
            headers: vec!["x".to_string(), "y".to_string(), "value".to_string()],
            rows: vec![
                vec!["0.0".to_string(), "0.0".to_string(), "10".to_string()],
                vec!["1.0".to_string(), "2.0".to_string(), "15".to_string()],
                vec!["2.0".to_string(), "1.5".to_string(), "8".to_string()],
                vec!["3.0".to_string(), "3.0".to_string(), "20".to_string()],
            ],
        }
    }

    pub fn to_points(&self) -> Result<Vec<[f32; 2]>, String> {
        if self.headers.len() < 2 {
            return Err("Need at least 2 columns".to_string());
        }

        let mut points = Vec::new();
        for row in &self.rows {
            if row.len() < 2 {
                continue;
            }

            let x = row[0].parse::<f32>().map_err(|_| "Invalid x coordinate")?;
            let y = row[1].parse::<f32>().map_err(|_| "Invalid y coordinate")?;
            points.push([x, y]);
        }

        Ok(points)
    }
}

// Example 5: Complex integration with multiple data sources

/// A data aggregator that combines multiple data sources
#[derive(Debug)]
pub struct DataAggregator {
    pub external_charts: Vec<ExternalChart>,
    pub csv_data: Vec<CsvData>,
    pub native_data: Vec<[f32; 2]>,
}

impl Default for DataAggregator {
    fn default() -> Self {
        Self::new()
    }
}

impl DataAggregator {
    pub fn new() -> Self {
        Self {
            external_charts: Vec::new(),
            csv_data: Vec::new(),
            native_data: Vec::new(),
        }
    }

    pub fn add_external_chart(&mut self, chart: ExternalChart) {
        self.external_charts.push(chart);
    }

    pub fn add_csv_data(&mut self, data: CsvData) {
        self.csv_data.push(data);
    }

    pub fn add_native_data(&mut self, points: Vec<[f32; 2]>) {
        self.native_data.extend(points);
    }

    /// Convert all data sources into a single Mixable visualization
    pub fn into_mixable(self) -> impl Mixable<Output = ()> {
        wrap_with_custom_render(self, |aggregator, _context| {
            // Render external charts
            for chart in &aggregator.external_charts {
                let chart_points: Vec<[f32; 2]> = chart
                    .data_points
                    .iter()
                    .map(|&(x, y)| [x as f32, y as f32])
                    .collect();

                if !chart_points.is_empty() {
                    // TODO: Render chart points using GPU pipeline
                    let _ = chart_points; // Suppress unused warning
                }
            }

            // Render CSV data
            for csv in &aggregator.csv_data {
                if let Ok(points) = csv.to_points() {
                    if !points.is_empty() {
                        // TODO: Render CSV points using GPU pipeline
                        let _ = points; // Suppress unused warning
                    }
                }
            }

            // Render native data
            if !aggregator.native_data.is_empty() {
                // TODO: Use context to render native points with GPU pipeline
                let _ = &aggregator.native_data; // Suppress unused warning
            }

            Ok(())
        })
    }
}

#[tokio::main]
async fn main() -> GupResult<()> {
    println!("Gup Integration Showcase");
    println!("========================\n");

    // Initialize render context
    let _context = RenderContext::new().await?;

    // Example 1: Using derive macro (auto-generated Mixable)
    println!("1. Auto-generated Mixable implementation:");
    let auto_scatter = AutoScatterPlot::new(
        vec![[0.0, 0.0], [1.0, 1.0], [2.0, 0.5]],
        [1.0, 0.0, 0.0, 1.0], // Red color
        5.0,                  // Size
    );
    println!("   Created: {}", auto_scatter.description());
    println!("   Valid: {}\n", auto_scatter.is_valid());

    // Example 2: Integration helpers for external types
    println!("2. External library integration:");
    let external_chart = ExternalChart::new_scatter(
        vec![(0.5, 0.5), (1.5, 1.5), (2.5, 0.8)],
        (0, 255, 0), // Green color
    );

    let wrapped_external = wrap_point_data(external_chart, |chart| {
        chart
            .data_points
            .iter()
            .map(|&(x, y)| [x as f32, y as f32])
            .collect()
    });
    println!("   Created: {}", wrapped_external.description());
    println!("   Valid: {}\n", wrapped_external.is_valid());

    // Example 3: Plugin system
    println!("3. Plugin system:");
    let mut registry = MixablePluginRegistry::new();
    let plugin = ExternalChartPlugin;
    registry
        .register_plugin(Box::new(plugin))
        .map_err(|e| GupError::InvalidDataFormat { message: e })?;

    let plugins = registry.list_plugins();
    println!("   Registered plugins: {plugins:?}");

    // Use plugin to create mixable
    let chart_for_plugin = ExternalChart::new_line(
        vec![(0.0, 1.0), (1.0, 2.0), (2.0, 1.5)],
        (0, 0, 255), // Blue color
        3,
    );

    if let Some(mixable_from_plugin) = registry.create_mixable(chart_for_plugin) {
        println!(
            "   Plugin-created mixable: {}",
            mixable_from_plugin.description()
        );
        println!("   Valid: {}\n", mixable_from_plugin.is_valid());
    }

    // Example 4: Data format conversion
    println!("4. Data format conversion:");
    let csv_data = CsvData::new();
    let points = csv_data.to_points().unwrap();
    println!("   Converted CSV to {} points", points.len());

    let csv_mixable = wrap_point_data(csv_data, |csv| csv.to_points().unwrap_or_default());
    println!("   CSV mixable: {}", csv_mixable.description());
    println!("   Valid: {}\n", csv_mixable.is_valid());

    // Example 5: Complex composition with multiple data sources
    println!("5. Multi-source composition:");
    let mut aggregator = DataAggregator::new();

    aggregator.add_external_chart(ExternalChart::new_scatter(
        vec![(3.0, 3.0), (4.0, 2.5)],
        (255, 165, 0), // Orange
    ));

    aggregator.add_csv_data(CsvData::new());
    aggregator.add_native_data(vec![[5.0, 1.0], [6.0, 2.0]]);

    let aggregated_mixable = aggregator.into_mixable();
    println!(
        "   Multi-source mixable: {}",
        aggregated_mixable.description()
    );
    println!("   Valid: {}\n", aggregated_mixable.is_valid());

    // Example 6: Composition with native Gup types
    println!("6. Composition with native types:");

    // Create a native scatter plot (would typically use Gup's built-in types)
    let native_points = vec![[7.0, 1.5], [8.0, 2.2], [9.0, 1.8]];
    let _native_mixable = wrap_point_data(native_points, |points| points.clone());

    // Compose auto-generated with external
    let composed = auto_scatter.mix(wrapped_external);
    println!("   Composed visualization: {}", composed.description());
    println!("   Valid: {}\n", composed.is_valid());

    // Example 7: Advanced composition with different modes
    println!("7. Advanced composition modes:");
    let chart1 = AutoScatterPlot::new(vec![[0.0, 0.0], [1.0, 1.0]], [1.0, 0.0, 0.0, 1.0], 3.0);

    let chart2 = AutoScatterPlot::new(vec![[0.5, 0.5], [1.5, 1.5]], [0.0, 1.0, 0.0, 1.0], 4.0);

    // Different composition modes
    let overlay = chart1.clone().overlay(chart2.clone());
    let side_by_side = chart1.clone().beside(chart2.clone());
    let merge = chart1.mix(chart2);

    println!("   Overlay: {}", overlay.description());
    println!("   Side-by-side: {}", side_by_side.description());
    println!("   Merge: {}", merge.description());

    println!("\n✓ Integration showcase completed successfully!");
    println!("\nKey takeaways:");
    println!("- Derive macro reduces boilerplate for custom types");
    println!("- Integration helpers make external libraries compatible");
    println!("- Plugin system enables ecosystem-wide integration");
    println!("- All integrated types compose naturally with existing Gup visualizations");
    println!("- Multiple data sources can be unified through composition");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio_test;

    #[test]
    fn test_auto_scatter_plot() {
        let scatter = AutoScatterPlot::new(vec![[0.0, 0.0], [1.0, 1.0]], [1.0, 0.0, 0.0, 1.0], 5.0);

        assert!(scatter.is_valid());
        assert!(scatter.description().contains("AutoScatterPlot"));
        assert!(scatter.description().contains("2 points"));
    }

    #[test]
    fn test_external_chart_creation() {
        let chart = ExternalChart::new_scatter(vec![(0.0, 0.0), (1.0, 1.0)], (255, 0, 0));

        assert_eq!(chart.data_points.len(), 2);
        matches!(chart.chart_type, ExternalChartType::Scatter);
    }

    #[test]
    fn test_csv_data_conversion() {
        let csv = CsvData::new();
        let points = csv.to_points().unwrap();

        assert_eq!(points.len(), 4);
        assert_eq!(points[0], [0.0, 0.0]);
        assert_eq!(points[1], [1.0, 2.0]);
    }

    #[tokio::test]
    async fn test_plugin_registry() {
        let mut registry = MixablePluginRegistry::new();
        let plugin = ExternalChartPlugin;

        assert!(registry.register_plugin(Box::new(plugin)).is_ok());
        assert_eq!(registry.list_plugins().len(), 1);
        assert!(registry.has_plugin("external_chart_library"));
    }

    #[test]
    fn test_data_aggregator() {
        let mut aggregator = DataAggregator::new();

        aggregator.add_external_chart(ExternalChart::new_scatter(vec![(1.0, 1.0)], (255, 0, 0)));

        aggregator.add_csv_data(CsvData::new());
        aggregator.add_native_data(vec![[2.0, 2.0]]);

        let mixable = aggregator.into_mixable();
        assert!(mixable.is_valid());
    }

    #[test]
    fn test_integration_composition() {
        let chart1 = AutoScatterPlot::new(vec![[0.0, 0.0]], [1.0, 0.0, 0.0, 1.0], 3.0);

        let chart2 = AutoScatterPlot::new(vec![[1.0, 1.0]], [0.0, 1.0, 0.0, 1.0], 4.0);

        let composed = chart1.mix(chart2);
        assert!(composed.is_valid());
        assert!(composed.description().contains("ComposedVisualization"));
    }
}
