// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! 3D Scatter Plot with Axes and Grid
//!
//! Extends the `scatter_3d` example with coloured X/Y/Z axes, tick marks,
//! and a ground-plane grid generated by [`Axis3D`] and [`Grid3D`].

use gup::GupContext;
use gup::axis3d::{Axis3D, Axis3DConfig, Grid3D, Grid3DConfig};
use gup::camera::Camera;
use gup::depth::{DEPTH_FORMAT, DepthBuffer};
use gup::lighting::{LightUniform, Material};
use gup::mark::Mark;
use gup::mark::line3d::{Line3D, Line3DInstance, Line3DVertex};
use gup::mark::sphere3d::{Sphere3D, Sphere3DInstance, Sphere3DVertex};
use std::sync::Arc;
use wgpu::util::DeviceExt;
use winit::{
    application::ApplicationHandler,
    event::{ElementState, KeyEvent, WindowEvent},
    event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
    keyboard::{KeyCode, PhysicalKey},
    window::{Window, WindowAttributes},
};

// ---------------------------------------------------------------------------
// Data generation
// ---------------------------------------------------------------------------

fn generate_scatter_data(count: usize) -> Vec<Sphere3DInstance> {
    let material = Material::default();
    let golden_ratio = (1.0 + 5.0_f32.sqrt()) / 2.0;
    let mut instances = Vec::with_capacity(count);

    for i in 0..count {
        let t = i as f32 / count as f32;
        let theta = 2.0 * std::f32::consts::PI * i as f32 / golden_ratio;
        let phi = (1.0 - 2.0 * (i as f32 + 0.5) / count as f32).acos();

        let r = 1.5 * (0.3 + 0.7 * t);
        let x = r * phi.sin() * theta.cos();
        let y = r * phi.sin() * theta.sin();
        let z = r * phi.cos();

        let cr = 0.3 + 0.7 * ((x + 1.5) / 3.0);
        let cg = 0.3 + 0.7 * ((y + 1.5) / 3.0);
        let cb = 0.3 + 0.7 * ((z + 1.5) / 3.0);

        instances.push(Sphere3DInstance {
            position: [x, y, z],
            radius: 0.02 + 0.03 * t,
            color: [cr, cg, cb, 1.0],
            material_albedo_ambient: [
                material.albedo[0],
                material.albedo[1],
                material.albedo[2],
                material.ambient,
            ],
            material_dss: [material.diffuse, material.specular, material.shininess, 0.0],
        });
    }
    instances
}

fn generate_axis_and_grid_data() -> Vec<Line3DInstance> {
    let axis = Axis3D::new(Axis3DConfig::default());
    let grid = Grid3D::new(Grid3DConfig {
        color: [0.25, 0.25, 0.25, 0.6],
        ..Default::default()
    });

    let mut lines = grid.generate_instances();
    lines.extend(axis.generate_instances());
    lines
}

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct App {
    window: Option<Arc<Window>>,
    context: Option<Arc<GupContext>>,
    gpu: Option<GpuResources>,
    frame_count: u64,
    start_time: std::time::Instant,
}

struct GpuResources {
    // Sphere pipeline
    sphere_pipeline: wgpu::RenderPipeline,
    sphere_vertex_buffer: wgpu::Buffer,
    sphere_index_buffer: wgpu::Buffer,
    #[allow(dead_code)]
    sphere_instance_buffer: wgpu::Buffer,
    sphere_instance_bg: wgpu::BindGroup,
    sphere_uniform_bg: wgpu::BindGroup,
    num_sphere_instances: u32,
    num_sphere_indices: u32,

    // Line pipeline
    line_pipeline: wgpu::RenderPipeline,
    line_vertex_buffer: wgpu::Buffer,
    line_index_buffer: wgpu::Buffer,
    #[allow(dead_code)]
    line_instance_buffer: wgpu::Buffer,
    line_instance_bg: wgpu::BindGroup,
    line_uniform_bg: wgpu::BindGroup,
    num_line_instances: u32,
    num_line_indices: u32,

    // Shared
    camera_buffer: wgpu::Buffer,
    depth_buffer: DepthBuffer,
}

impl App {
    fn new() -> Self {
        Self {
            window: None,
            context: None,
            gpu: None,
            frame_count: 0,
            start_time: std::time::Instant::now(),
        }
    }

    fn create_gpu_resources(
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        width: u32,
        height: u32,
    ) -> GpuResources {
        // ----- Camera -----
        let aspect = width as f32 / height.max(1) as f32;
        let mut camera = Camera::perspective(std::f32::consts::FRAC_PI_4, aspect, 0.1, 100.0);
        camera.look_at(
            gup::shader_function::Vec3::new(0.0, 0.0, 5.0),
            gup::shader_function::Vec3::new(0.0, 0.0, 0.0),
            gup::shader_function::Vec3::new(0.0, 1.0, 0.0),
        );

        let camera_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("camera_uniform"),
            contents: bytemuck::bytes_of(&camera.to_uniform()),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });

        let light = LightUniform::default();
        let light_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("light_uniform"),
            contents: bytemuck::bytes_of(&light),
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        });
        queue.write_buffer(&light_buffer, 0, bytemuck::bytes_of(&light));

        // ----- Sphere resources -----
        let sphere_instances = generate_scatter_data(800);
        let num_sphere_instances = sphere_instances.len() as u32;

        let sphere_vertices = Sphere3D::generate_vertices();
        let sphere_indices = Sphere3D::generate_indices().unwrap();
        let num_sphere_indices = sphere_indices.len() as u32;

        let sphere_vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("sphere_vb"),
            contents: bytemuck::cast_slice(&sphere_vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });
        let sphere_index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("sphere_ib"),
            contents: bytemuck::cast_slice(&sphere_indices),
            usage: wgpu::BufferUsages::INDEX,
        });
        let sphere_instance_buffer =
            device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("sphere_instances"),
                contents: bytemuck::cast_slice(&sphere_instances),
                usage: wgpu::BufferUsages::STORAGE,
            });

        // Sphere bind group layouts
        let sphere_instance_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("sphere_instance_bgl"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let sphere_uniform_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("sphere_uniform_bgl"),
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            });

        let sphere_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("sphere_instance_bg"),
            layout: &sphere_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: sphere_instance_buffer.as_entire_binding(),
            }],
        });

        let sphere_uniform_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("sphere_uniform_bg"),
            layout: &sphere_uniform_bgl,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: camera_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: light_buffer.as_entire_binding(),
                },
            ],
        });

        // Sphere pipeline
        let sphere_vert = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("sphere_vert"),
            source: wgpu::ShaderSource::Wgsl(Sphere3D::VERTEX_SHADER.unwrap().into()),
        });
        let sphere_frag = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("sphere_frag"),
            source: wgpu::ShaderSource::Wgsl(Sphere3D::FRAGMENT_SHADER.unwrap().into()),
        });

        let sphere_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("sphere_pl"),
                bind_group_layouts: &[&sphere_instance_bgl, &sphere_uniform_bgl],
                push_constant_ranges: &[],
            });

        let sphere_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("sphere_pipeline"),
            layout: Some(&sphere_pipeline_layout),
            vertex: wgpu::VertexState {
                module: &sphere_vert,
                entry_point: Some("vs_main"),
                buffers: &[wgpu::VertexBufferLayout {
                    array_stride: std::mem::size_of::<Sphere3DVertex>() as wgpu::BufferAddress,
                    step_mode: wgpu::VertexStepMode::Vertex,
                    attributes: &[wgpu::VertexAttribute {
                        offset: 0,
                        shader_location: 0,
                        format: wgpu::VertexFormat::Float32x2,
                    }],
                }],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &sphere_frag,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: wgpu::TextureFormat::Bgra8UnormSrgb,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: DEPTH_FORMAT,
                depth_write_enabled: true,
                depth_compare: wgpu::CompareFunction::Less,
                stencil: wgpu::StencilState::default(),
                bias: wgpu::DepthBiasState::default(),
            }),
            multisample: wgpu::MultisampleState::default(),
            multiview: None,
            cache: None,
        });

        // ----- Line3D resources (axes + grid) -----
        let line_instances = generate_axis_and_grid_data();
        let num_line_instances = line_instances.len() as u32;

        let line_vertices = Line3D::generate_vertices();
        let line_indices = Line3D::generate_indices().unwrap();
        let num_line_indices = line_indices.len() as u32;

        let line_vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("line_vb"),
            contents: bytemuck::cast_slice(&line_vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });
        let line_index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("line_ib"),
            contents: bytemuck::cast_slice(&line_indices),
            usage: wgpu::BufferUsages::INDEX,
        });
        let line_instance_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("line_instances"),
            contents: bytemuck::cast_slice(&line_instances),
            usage: wgpu::BufferUsages::STORAGE,
        });

        // Line bind group layouts — group 0: instance storage, group 1: camera
        let line_instance_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("line_instance_bgl"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::VERTEX,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Storage { read_only: true },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            }],
        });

        let line_uniform_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("line_uniform_bgl"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::VERTEX,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            }],
        });

        let line_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("line_instance_bg"),
            layout: &line_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: line_instance_buffer.as_entire_binding(),
            }],
        });

        let line_uniform_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("line_uniform_bg"),
            layout: &line_uniform_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: camera_buffer.as_entire_binding(),
            }],
        });

        // Line shader & pipeline
        let line_vert = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("line3d_vert"),
            source: wgpu::ShaderSource::Wgsl(Line3D::VERTEX_SHADER.unwrap().into()),
        });
        let line_frag = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("line3d_frag"),
            source: wgpu::ShaderSource::Wgsl(Line3D::FRAGMENT_SHADER.unwrap().into()),
        });

        let line_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("line_pl"),
                bind_group_layouts: &[&line_instance_bgl, &line_uniform_bgl],
                push_constant_ranges: &[],
            });

        let line_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("line_pipeline"),
            layout: Some(&line_pipeline_layout),
            vertex: wgpu::VertexState {
                module: &line_vert,
                entry_point: Some("vs_main"),
                buffers: &[wgpu::VertexBufferLayout {
                    array_stride: std::mem::size_of::<Line3DVertex>() as wgpu::BufferAddress,
                    step_mode: wgpu::VertexStepMode::Vertex,
                    attributes: &[wgpu::VertexAttribute {
                        offset: 0,
                        shader_location: 0,
                        format: wgpu::VertexFormat::Float32x2,
                    }],
                }],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &line_frag,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: wgpu::TextureFormat::Bgra8UnormSrgb,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: DEPTH_FORMAT,
                depth_write_enabled: true,
                depth_compare: wgpu::CompareFunction::Less,
                stencil: wgpu::StencilState::default(),
                bias: wgpu::DepthBiasState::default(),
            }),
            multisample: wgpu::MultisampleState::default(),
            multiview: None,
            cache: None,
        });

        let depth_buffer = DepthBuffer::new(device, width, height);

        GpuResources {
            sphere_pipeline,
            sphere_vertex_buffer,
            sphere_index_buffer,
            sphere_instance_buffer,
            sphere_instance_bg,
            sphere_uniform_bg,
            num_sphere_instances,
            num_sphere_indices,
            line_pipeline,
            line_vertex_buffer,
            line_index_buffer,
            line_instance_buffer,
            line_instance_bg,
            line_uniform_bg,
            num_line_instances,
            num_line_indices,
            camera_buffer,
            depth_buffer,
        }
    }

    fn render_frame(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let Some(context) = self.context.take() else {
            return Ok(());
        };
        let mut ctx = Arc::try_unwrap(context).map_err(|_| "cannot unwrap Arc")?;

        if self.gpu.is_none() {
            let size = self.window.as_ref().unwrap().inner_size();
            self.gpu = Some(Self::create_gpu_resources(
                &ctx.device,
                &ctx.queue,
                size.width,
                size.height,
            ));
            println!(
                "✓ GPU resources: {} spheres, {} line instances (axes + grid)",
                self.gpu.as_ref().unwrap().num_sphere_instances,
                self.gpu.as_ref().unwrap().num_line_instances,
            );
        }

        // Orbit camera.
        let elapsed = self.start_time.elapsed().as_secs_f32();
        let angle = elapsed * 0.4;
        let eye_dist = 5.0;
        let eye = gup::shader_function::Vec3::new(
            eye_dist * angle.cos(),
            2.0,
            eye_dist * angle.sin(),
        );

        let size = self.window.as_ref().unwrap().inner_size();
        let aspect = size.width as f32 / size.height.max(1) as f32;
        let mut camera = Camera::perspective(std::f32::consts::FRAC_PI_4, aspect, 0.1, 100.0);
        camera.look_at(
            eye,
            gup::shader_function::Vec3::new(0.0, 0.0, 0.0),
            gup::shader_function::Vec3::new(0.0, 1.0, 0.0),
        );
        let camera_uniform = camera.to_uniform();

        let gpu = self.gpu.as_ref().unwrap();
        ctx.queue
            .write_buffer(&gpu.camera_buffer, 0, bytemuck::bytes_of(&camera_uniform));

        match ctx.begin_frame() {
            Ok(mut frame) => {
                {
                    let mut pass = frame.render_pass_with_depth(
                        Some(wgpu::Color {
                            r: 0.04,
                            g: 0.04,
                            b: 0.08,
                            a: 1.0,
                        }),
                        gpu.depth_buffer.view(),
                    );

                    // Draw grid + axis lines first (behind spheres via depth).
                    pass.set_pipeline(&gpu.line_pipeline);
                    pass.set_bind_group(0, &gpu.line_instance_bg, &[]);
                    pass.set_bind_group(1, &gpu.line_uniform_bg, &[]);
                    pass.set_vertex_buffer(0, gpu.line_vertex_buffer.slice(..));
                    pass.set_index_buffer(
                        gpu.line_index_buffer.slice(..),
                        wgpu::IndexFormat::Uint32,
                    );
                    pass.draw_indexed(0..gpu.num_line_indices, 0, 0..gpu.num_line_instances);

                    // Draw spheres.
                    pass.set_pipeline(&gpu.sphere_pipeline);
                    pass.set_bind_group(0, &gpu.sphere_instance_bg, &[]);
                    pass.set_bind_group(1, &gpu.sphere_uniform_bg, &[]);
                    pass.set_vertex_buffer(0, gpu.sphere_vertex_buffer.slice(..));
                    pass.set_index_buffer(
                        gpu.sphere_index_buffer.slice(..),
                        wgpu::IndexFormat::Uint32,
                    );
                    pass.draw_indexed(
                        0..gpu.num_sphere_indices,
                        0,
                        0..gpu.num_sphere_instances,
                    );
                }

                frame.finish()?;
                self.frame_count += 1;

                if self.frame_count.is_multiple_of(120) {
                    let stats = ctx.frame_stats();
                    println!(
                        "Frame {}: {:.1} FPS, {:.2}ms avg",
                        self.frame_count,
                        stats.fps(),
                        stats.avg_frame_time,
                    );
                }
            }
            Err(e) => eprintln!("begin_frame error: {e}"),
        }

        self.context = Some(Arc::new(ctx));
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// winit ApplicationHandler
// ---------------------------------------------------------------------------

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        println!("=== Gup 3D Scatter Plot with Axes & Grid ===");

        pollster::block_on(async {
            let attrs = WindowAttributes::default()
                .with_title("Gup 3D Scatter + Axes — Q to quit")
                .with_inner_size(winit::dpi::LogicalSize::new(900, 700));

            let window = Arc::new(event_loop.create_window(attrs).expect("create window"));
            let context = GupContext::with_surface(Arc::clone(&window))
                .await
                .expect("create GPU context");

            self.window = Some(window);
            self.context = Some(context);
            println!("✓ Window + GPU context ready");
        });
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        _window_id: winit::window::WindowId,
        event: WindowEvent,
    ) {
        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::KeyboardInput {
                event:
                    KeyEvent {
                        physical_key: PhysicalKey::Code(KeyCode::KeyQ),
                        state: ElementState::Pressed,
                        ..
                    },
                ..
            } => event_loop.exit(),
            WindowEvent::Resized(size) => {
                if let Some(context) = self.context.take()
                    && let Ok(mut ctx) = Arc::try_unwrap(context)
                {
                    let _ = ctx.resize_surface(
                        ctx.primary_surface_id().unwrap(),
                        gup::PhysicalSize::new(size.width, size.height),
                    );
                    if let Some(gpu) = self.gpu.as_mut() {
                        gpu.depth_buffer
                            .resize(&ctx.device, size.width, size.height);
                    }
                    self.context = Some(Arc::new(ctx));
                }
            }
            WindowEvent::RedrawRequested => {
                if let Err(e) = self.render_frame() {
                    eprintln!("render error: {e}");
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        if let Some(window) = &self.window {
            window.request_redraw();
        }
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let event_loop = EventLoop::new()?;
    event_loop.set_control_flow(ControlFlow::Poll);
    let mut app = App::new();
    event_loop.run_app(&mut app)?;
    Ok(())
}
