#!/usr/bin/env bash
# Copyright (C) 2025 Corin Lawson
# SPDX-License-Identifier: GPL-3.0-or-later

# Generate interaction system performance report (GUP-077)
# Runs interaction benchmarks and produces a Markdown report.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPORT_FILE="${1:-${PROJECT_ROOT}/interaction_performance_report.md}"

cd "${PROJECT_ROOT}"

echo "Running interaction benchmarks..."
BENCH_OUTPUT=$(cargo bench --bench interaction_benchmarks 2>&1 || true)

echo "Running interaction memory benchmarks..."
MEMORY_OUTPUT=$(cargo bench --bench interaction_memory_benchmarks 2>&1 || true)

echo "Running interaction integration tests (performance)..."
TEST_OUTPUT=$(cargo test --test interaction_system_tests -- --test-threads=1 --nocapture 2>&1 || true)

# Extract system info
GPU_INFO=""
if command -v lspci &>/dev/null; then
    GPU_INFO=$(lspci 2>/dev/null | grep -i 'vga\|3d\|display' | head -1 || echo "unknown")
fi

cat > "$REPORT_FILE" <<EOF
# Interaction System Performance Report

**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Story**: GUP-077 Performance Benchmarking Suite

## System Information

- **Platform**: $(uname -s) $(uname -r)
- **Architecture**: $(uname -m)
- **Rust Version**: $(rustc --version)
- **GPU**: ${GPU_INFO:-unknown}

## Performance Targets

Based on GUP-014 goals:

| Metric | Target | Notes |
|--------|--------|-------|
| Point Queries (1M pts) | <1ms | With spatial indexing |
| Region Queries (1M pts, 10%) | <10ms | 10% region coverage |
| Memory Overhead | <5% | For spatial structures |
| Batch vs Individual | 10× throughput | Batch query advantage |

## Benchmark Results

### Query Performance

\`\`\`
$(echo "$BENCH_OUTPUT" | grep -E '(point_queries|region_queries|batch_queries|streaming_queries|scaling)' || echo "No matching benchmark output")
\`\`\`

### Full Benchmark Output

\`\`\`
$BENCH_OUTPUT
\`\`\`

### Memory and Resource Benchmarks

\`\`\`
$MEMORY_OUTPUT
\`\`\`

## Integration Test Results

\`\`\`
$TEST_OUTPUT
\`\`\`

## Coverage Summary

### APIs Benchmarked

- [x] \`query_point()\` — single point hit testing
- [x] \`query_region()\` — rectangular area queries
- [x] \`query_batch()\` — multiple simultaneous queries
- [x] \`query_stream()\` — chunked streaming for large datasets

### Dataset Patterns

- [x] Grid pattern (evenly spaced)
- [x] Clustered pattern (dense groups)

### Dataset Sizes Tested

- [x] 100, 500, 1,000 elements
- [x] 5,000, 10,000 elements
- [x] 50,000, 100,000 elements

### Resource Benchmarks

- [x] Spatial index build time
- [x] Selection creation overhead
- [x] Element extraction cost
- [x] InteractionSystem creation
- [x] First vs subsequent query (caching)

---

*Generated by scripts/interaction_performance_report.sh*
EOF

echo "Report generated: $REPORT_FILE"
echo ""
echo "Summary of benchmark results:"
echo "$BENCH_OUTPUT" | grep -E 'time:' | head -20 || echo "(no timing data captured)"
