// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! WGSL code generator — converts the AST back into WGSL text.
//!
//! Produces properly formatted, indented WGSL from a [`WgslModule`].

use super::types::*;

/// Configuration for the WGSL code generator.
#[derive(Debug, Clone)]
pub struct GeneratorConfig {
    /// Number of spaces per indentation level.
    pub indent_spaces: usize,
    /// Whether to include a header comment.
    pub include_header: bool,
}

impl Default for GeneratorConfig {
    fn default() -> Self {
        Self {
            indent_spaces: 4,
            include_header: true,
        }
    }
}

/// Generates WGSL source text from an AST.
pub struct WgslGenerator {
    config: GeneratorConfig,
    output: String,
    indent_level: usize,
}

impl WgslGenerator {
    pub fn new(config: GeneratorConfig) -> Self {
        Self {
            config,
            output: String::new(),
            indent_level: 0,
        }
    }

    /// Generate WGSL text from a module.
    pub fn generate(&mut self, module: &WgslModule) -> String {
        self.output.clear();

        if self.config.include_header {
            self.write_line("// Generated by Gup shader AST system");
            self.write_line("");
        }

        // Emit structs.
        for (i, s) in module.structs.iter().enumerate() {
            self.generate_struct(s);
            if i + 1 < module.structs.len()
                || !module.globals.is_empty()
                || !module.functions.is_empty()
            {
                self.write_line("");
            }
        }

        // Emit globals.
        for (i, g) in module.globals.iter().enumerate() {
            self.generate_global(g);
            if i + 1 < module.globals.len() || !module.functions.is_empty() {
                self.write_line("");
            }
        }

        // Emit functions.
        for (i, f) in module.functions.iter().enumerate() {
            self.generate_function(f);
            if i + 1 < module.functions.len() {
                self.write_line("");
            }
        }

        self.output.clone()
    }

    // --- Struct ---

    fn generate_struct(&mut self, s: &StructDef) {
        self.write_indent();
        self.write(&format!("struct {} {{\n", s.name));
        self.indent_level += 1;
        for field in &s.fields {
            self.write_indent();
            for attr in &field.attributes {
                self.write(&format!("{attr} "));
            }
            self.write(&format!("{}: {},\n", field.name, field.ty));
        }
        self.indent_level -= 1;
        self.write_indent();
        self.write("}\n");
    }

    // --- Global ---

    fn generate_global(&mut self, g: &GlobalVar) {
        self.write_indent();
        for attr in &g.attributes {
            self.write(&format!("{attr} "));
        }
        self.write(&format!("var<{}> {}: {};\n", g.address_space, g.name, g.ty));
    }

    // --- Function ---

    fn generate_function(&mut self, f: &Function) {
        self.write_indent();
        for attr in &f.attributes {
            self.write(&format!("{attr}\n"));
            self.write_indent();
        }

        self.write(&format!("fn {}(", f.name));
        for (i, param) in f.parameters.iter().enumerate() {
            if i > 0 {
                self.write(", ");
            }
            self.write(&format!("{}: {}", param.name, param.ty));
        }
        self.write(")");

        if let Some(ref ret) = f.return_type {
            self.write(" -> ");
            for attr in &f.return_attributes {
                self.write(&format!("{attr} "));
            }
            self.write(&format!("{ret}"));
        }

        self.write(" {\n");
        self.indent_level += 1;
        self.generate_block_contents(&f.body);
        self.indent_level -= 1;
        self.write_indent();
        self.write("}\n");
    }

    // --- Statements ---

    fn generate_block_contents(&mut self, block: &Block) {
        for stmt in &block.statements {
            self.generate_statement(stmt);
        }
    }

    fn generate_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let {
                name,
                ty,
                value,
                mutable,
            } => {
                self.write_indent();
                let kw = if *mutable { "var" } else { "let" };
                if let Some(t) = ty {
                    self.write(&format!("{kw} {name}: {t} = "));
                } else {
                    self.write(&format!("{kw} {name} = "));
                }
                self.generate_expr(value);
                self.write(";\n");
            }
            Statement::Assign(target, value) => {
                self.write_indent();
                self.generate_expr(target);
                self.write(" = ");
                self.generate_expr(value);
                self.write(";\n");
            }
            Statement::Return(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    self.write("return ");
                    self.generate_expr(e);
                    self.write(";\n");
                } else {
                    self.write("return;\n");
                }
            }
            Statement::If {
                condition,
                body,
                else_body,
            } => {
                self.write_indent();
                self.write("if (");
                self.generate_expr(condition);
                self.write(") {\n");
                self.indent_level += 1;
                self.generate_block_contents(body);
                self.indent_level -= 1;
                self.write_indent();
                if let Some(eb) = else_body {
                    self.write("} else {\n");
                    self.indent_level += 1;
                    self.generate_block_contents(eb);
                    self.indent_level -= 1;
                    self.write_indent();
                    self.write("}\n");
                } else {
                    self.write("}\n");
                }
            }
            Statement::For {
                init,
                condition,
                update,
                body,
            } => {
                self.write_indent();
                self.write("for (");
                if let Some(init_stmt) = init {
                    self.generate_inline_statement(init_stmt);
                }
                self.write("; ");
                if let Some(cond) = condition {
                    self.generate_expr(cond);
                }
                self.write("; ");
                if let Some(upd) = update {
                    self.generate_inline_statement(upd);
                }
                self.write(") {\n");
                self.indent_level += 1;
                self.generate_block_contents(body);
                self.indent_level -= 1;
                self.write_indent();
                self.write("}\n");
            }
            Statement::Expression(expr) => {
                self.write_indent();
                self.generate_expr(expr);
                self.write(";\n");
            }
            Statement::Block(block) => {
                self.write_indent();
                self.write("{\n");
                self.indent_level += 1;
                self.generate_block_contents(block);
                self.indent_level -= 1;
                self.write_indent();
                self.write("}\n");
            }
        }
    }

    /// Generate an inline statement (used inside `for` headers).
    fn generate_inline_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let {
                name,
                ty,
                value,
                mutable,
            } => {
                let kw = if *mutable { "var" } else { "let" };
                if let Some(t) = ty {
                    self.write(&format!("{kw} {name}: {t} = "));
                } else {
                    self.write(&format!("{kw} {name} = "));
                }
                self.generate_expr(value);
            }
            Statement::Assign(target, value) => {
                self.generate_expr(target);
                self.write(" = ");
                self.generate_expr(value);
            }
            Statement::Expression(expr) => {
                self.generate_expr(expr);
            }
            _ => {}
        }
    }

    // --- Expressions ---

    fn generate_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal(lit) => match lit {
                Literal::Float(v) => {
                    // Ensure float has decimal point
                    let s = format!("{v}");
                    if s.contains('.') {
                        self.write(&s);
                    } else {
                        self.write(&format!("{s}.0"));
                    }
                }
                Literal::Int(v) => self.write(&format!("{v}")),
                Literal::UInt(v) => self.write(&format!("{v}u")),
                Literal::Bool(v) => self.write(&format!("{v}")),
            },
            Expr::Ident(name) => self.write(name),
            Expr::Binary(left, op, right) => {
                // Add parens around sub-expressions for clarity
                let needs_left_parens = matches!(**left, Expr::Binary(_, _, _));
                let needs_right_parens = matches!(**right, Expr::Binary(_, _, _));

                if needs_left_parens {
                    self.write("(");
                }
                self.generate_expr(left);
                if needs_left_parens {
                    self.write(")");
                }

                self.write(&format!(" {op} "));

                if needs_right_parens {
                    self.write("(");
                }
                self.generate_expr(right);
                if needs_right_parens {
                    self.write(")");
                }
            }
            Expr::Unary(op, inner) => {
                match op {
                    UnaryOp::Negate => self.write("-"),
                    UnaryOp::Not => self.write("!"),
                }
                self.generate_expr(inner);
            }
            Expr::Call(name, args) => {
                self.write(&format!("{name}("));
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.generate_expr(arg);
                }
                self.write(")");
            }
            Expr::TypeConstructor(ty, args) => {
                self.write(&format!("{ty}("));
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.generate_expr(arg);
                }
                self.write(")");
            }
            Expr::MemberAccess(base, field) => {
                self.generate_expr(base);
                self.write(&format!(".{field}"));
            }
            Expr::IndexAccess(base, index) => {
                self.generate_expr(base);
                self.write("[");
                self.generate_expr(index);
                self.write("]");
            }
        }
    }

    // --- Output helpers ---

    fn write(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn write_indent(&mut self) {
        let spaces = self.indent_level * self.config.indent_spaces;
        for _ in 0..spaces {
            self.output.push(' ');
        }
    }

    fn write_line(&mut self, s: &str) {
        self.write_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }
}

/// Convenience function to generate WGSL from a module with default settings.
pub fn generate_wgsl(module: &WgslModule) -> String {
    let mut generator = WgslGenerator::new(GeneratorConfig::default());
    generator.generate(module)
}

/// Generate WGSL without a header comment.
pub fn generate_wgsl_minimal(module: &WgslModule) -> String {
    let mut generator = WgslGenerator::new(GeneratorConfig {
        include_header: false,
        ..Default::default()
    });
    generator.generate(module)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shader_ast::parser::parse_wgsl;

    #[test]
    fn test_generate_simple_function() {
        let module = WgslModule {
            structs: vec![],
            globals: vec![],
            functions: vec![Function {
                name: "add_one".to_string(),
                parameters: vec![Parameter {
                    name: "value".to_string(),
                    ty: WgslType::Scalar(ScalarType::F32),
                }],
                return_type: Some(WgslType::Scalar(ScalarType::F32)),
                body: Block::new(vec![Statement::Return(Some(Expr::Binary(
                    Box::new(Expr::Ident("value".to_string())),
                    BinaryOp::Add,
                    Box::new(Expr::Literal(Literal::Float(1.0))),
                )))]),
                attributes: vec![],
                return_attributes: vec![],
            }],
        };

        let wgsl = generate_wgsl_minimal(&module);
        assert!(wgsl.contains("fn add_one(value: f32) -> f32"));
        assert!(wgsl.contains("return value + 1.0;"));
    }

    #[test]
    fn test_generate_struct() {
        let module = WgslModule {
            structs: vec![StructDef {
                name: "Uniforms".to_string(),
                fields: vec![
                    StructField {
                        name: "scale".to_string(),
                        ty: WgslType::Scalar(ScalarType::F32),
                        attributes: vec![],
                    },
                    StructField {
                        name: "offset".to_string(),
                        ty: WgslType::Vector(ScalarType::F32, 2),
                        attributes: vec![],
                    },
                ],
            }],
            globals: vec![],
            functions: vec![],
        };

        let wgsl = generate_wgsl_minimal(&module);
        assert!(wgsl.contains("struct Uniforms {"));
        assert!(wgsl.contains("scale: f32,"));
        assert!(wgsl.contains("offset: vec2<f32>,"));
    }

    #[test]
    fn test_generate_global_var() {
        let module = WgslModule {
            structs: vec![],
            globals: vec![GlobalVar {
                name: "my_uniform".to_string(),
                ty: WgslType::Struct("Uniforms".to_string()),
                address_space: AddressSpace::Uniform,
                attributes: vec![Attribute::Group(0), Attribute::Binding(0)],
            }],
            functions: vec![],
        };

        let wgsl = generate_wgsl_minimal(&module);
        assert!(wgsl.contains("@group(0)"));
        assert!(wgsl.contains("@binding(0)"));
        assert!(wgsl.contains("var<uniform> my_uniform: Uniforms;"));
    }

    #[test]
    fn test_roundtrip_simple_function() {
        let source = r#"fn linear_scale(value: f32, uniforms: LinearScaleUniforms) -> f32 {
    let normalized = (value - uniforms.domain_min) / (uniforms.domain_max - uniforms.domain_min);
    return uniforms.range_min + normalized * (uniforms.range_max - uniforms.range_min);
}"#;

        // Parse
        let module = parse_wgsl(source).unwrap();
        assert_eq!(module.functions.len(), 1);
        assert_eq!(module.functions[0].name, "linear_scale");
        assert_eq!(module.functions[0].parameters.len(), 2);

        // Generate
        let generated = generate_wgsl_minimal(&module);

        // Verify key semantics are preserved
        assert!(
            generated.contains("fn linear_scale(value: f32, uniforms: LinearScaleUniforms) -> f32")
        );
        assert!(generated.contains("normalized"));
        assert!(generated.contains("uniforms.domain_min"));
        assert!(generated.contains("uniforms.range_min"));
    }

    #[test]
    fn test_roundtrip_struct_and_function() {
        let source = r#"
struct Uniforms {
    scale: f32,
    offset: vec2<f32>,
}

@group(0) @binding(0) var<uniform> u: Uniforms;

fn transform(pos: vec2<f32>) -> vec4<f32> {
    let scaled = pos * u.scale;
    return vec4<f32>(scaled + u.offset, 0.0, 1.0);
}
"#;

        let module = parse_wgsl(source).unwrap();
        assert_eq!(module.structs.len(), 1);
        assert_eq!(module.globals.len(), 1);
        assert_eq!(module.functions.len(), 1);

        let generated = generate_wgsl_minimal(&module);
        assert!(generated.contains("struct Uniforms"));
        assert!(generated.contains("var<uniform> u: Uniforms;"));
        assert!(generated.contains("fn transform(pos: vec2<f32>) -> vec4<f32>"));
    }

    #[test]
    fn test_roundtrip_if_else() {
        let source = r#"
fn clamp_val(x: f32) -> f32 {
    if (x > 1.0) {
        return 1.0;
    } else {
        return x;
    }
}
"#;

        let module = parse_wgsl(source).unwrap();
        let generated = generate_wgsl_minimal(&module);
        assert!(generated.contains("if ("));
        assert!(generated.contains("} else {"));
        assert!(generated.contains("return 1.0;"));
        assert!(generated.contains("return x;"));
    }

    #[test]
    fn test_generate_vertex_attribute() {
        let module = WgslModule {
            structs: vec![],
            globals: vec![],
            functions: vec![Function {
                name: "vs_main".to_string(),
                parameters: vec![],
                return_type: Some(WgslType::Struct("VertexOutput".to_string())),
                body: Block::empty(),
                attributes: vec![Attribute::Vertex],
                return_attributes: vec![],
            }],
        };

        let wgsl = generate_wgsl_minimal(&module);
        assert!(wgsl.contains("@vertex"));
        assert!(wgsl.contains("fn vs_main()"));
    }
}
