// Gup - GPU-Accelerated Data Visualization Library
// Copyright (C) 2025 Corin Lawson <corin@phiware.com.au>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! MarkTypeId derive macro implementation for stable mark type IDs.

use proc_macro2::TokenStream;
use quote::quote;
use syn::{DeriveInput, Lit, Meta, Result};

/// Generate the MarkTypeId implementation for a mark type.
pub fn derive_mark_type_id_impl(input: DeriveInput) -> Result<TokenStream> {
    let name = &input.ident;

    // Look for #[mark_type_id = N] attribute
    let mark_type_id = extract_mark_type_id(&input)?;

    // Validate the ID is in valid range (0-255)
    if mark_type_id > 255 {
        return Err(syn::Error::new_spanned(
            &input,
            format!("mark_type_id must be in range 0-255, got {}", mark_type_id),
        ));
    }

    let doc_comment = format!(
        "Mark type ID for GPU interaction system.\n\n\
         This constant is automatically generated by the MarkTypeId derive macro.\n\
         The value {} corresponds to the mark type's ID in GPU shaders.",
        mark_type_id
    );

    let expanded = quote! {
        impl #name {
            #[doc = #doc_comment]
            pub const MARK_TYPE_ID: u32 = #mark_type_id;
        }

        impl crate::mark::MarkTypeIdProvider for #name {
            fn mark_type_id() -> u32 {
                Self::MARK_TYPE_ID
            }
        }
    };

    Ok(expanded)
}

/// Extract the mark_type_id value from attributes.
fn extract_mark_type_id(input: &DeriveInput) -> Result<u32> {
    for attr in &input.attrs {
        if attr.path().is_ident("mark_type_id") {
            // Parse #[mark_type_id = N]
            let meta = &attr.meta;
            if let Meta::NameValue(nv) = meta
                && let syn::Expr::Lit(expr_lit) = &nv.value
                && let Lit::Int(lit_int) = &expr_lit.lit
            {
                return lit_int.base10_parse();
            }
            return Err(syn::Error::new_spanned(
                attr,
                "mark_type_id attribute must be in the form #[mark_type_id = N] where N is an integer",
            ));
        }
    }

    // No explicit ID provided - error for now, we'll handle auto-assignment later if needed
    Err(syn::Error::new_spanned(
        input,
        "MarkTypeId derive requires a #[mark_type_id = N] attribute. \
         Example: #[derive(MarkTypeId)] #[mark_type_id = 0]",
    ))
}
