// Copyright (C) 2024 Corin Lawson
// SPDX-License-Identifier: GPL-3.0-or-later

//! The [`GupWidget`] stateful widget and [`DynChart`] trait.

use egui::{ColorImage, TextureHandle, TextureOptions};
use gup::chart_builder::ComposedChart;
use gup::error::GupResult;
use gup::render::RenderContext;

use crate::bridge;

// ---------------------------------------------------------------------------
// DynChart — object-safe chart rendering trait
// ---------------------------------------------------------------------------

/// Object-safe trait that allows type-erased chart rendering.
///
/// Implemented automatically for any [`ComposedChart<T, M>`] whose type
/// parameters satisfy the required bounds, so users never need to implement
/// this trait manually.
pub trait DynChart: Send + Sync + 'static {
    /// Prepare GPU resources and record draw commands.
    fn render(&mut self, context: &mut RenderContext) -> GupResult<()>;

    /// Render the chart to PNG bytes at the given pixel dimensions.
    fn render_to_png(&mut self, width: u32, height: u32) -> GupResult<Vec<u8>>;
}

impl<T, M> DynChart for ComposedChart<T, M>
where
    T: Clone + Send + Sync + std::fmt::Debug + 'static,
    M: gup::mark::Mark,
{
    fn render(&mut self, context: &mut RenderContext) -> GupResult<()> {
        ComposedChart::render(self, context)
    }

    fn render_to_png(&mut self, width: u32, height: u32) -> GupResult<Vec<u8>> {
        ComposedChart::render_to_png(self, width, height)
    }
}

// ---------------------------------------------------------------------------
// GupWidget — stateful egui widget
// ---------------------------------------------------------------------------

/// A stateful egui widget that renders a Gup chart inside any egui panel.
///
/// The chart is rendered off-screen to a GPU texture via Gup's rendering
/// pipeline, then uploaded to egui's texture manager as a
/// [`ColorImage`](egui::ColorImage). Re-renders only happen when the chart
/// data or panel size has changed.
///
/// # Usage
///
/// ```rust,ignore
/// // Create once, store in your app state:
/// let mut widget = GupWidget::new(my_chart);
///
/// // Each frame, inside an egui panel:
/// ui.add(&mut widget);
///
/// // When data changes:
/// widget.mark_dirty();
/// ```
pub struct GupWidget {
    /// The type-erased chart.
    chart: Box<dyn DynChart>,
    /// Internal dirty flag — set when the chart needs re-rendering.
    dirty: bool,
    /// The last rendered size (width, height) in physical pixels.
    last_size: Option<[u32; 2]>,
    /// Cached egui texture handle from the previous render.
    texture_handle: Option<TextureHandle>,
    /// Translated interaction events from the most recent frame.
    pending_events: Vec<gup::interaction::InteractionEvent>,
}

impl GupWidget {
    /// Create a new `GupWidget` wrapping any chart that implements [`DynChart`].
    ///
    /// The widget starts in the dirty state so the first frame triggers a
    /// render.
    pub fn new(chart: impl DynChart) -> Self {
        Self {
            chart: Box::new(chart),
            dirty: true,
            last_size: None,
            texture_handle: None,
            pending_events: Vec::new(),
        }
    }

    /// Mark the chart as needing a re-render on the next frame.
    ///
    /// Call this whenever the underlying chart data has changed.
    pub fn mark_dirty(&mut self) {
        self.dirty = true;
    }

    /// Returns `true` if the chart will be re-rendered on the next frame.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Borrow the inner chart for direct manipulation.
    pub fn chart(&self) -> &dyn DynChart {
        &*self.chart
    }

    /// Mutably borrow the inner chart.
    pub fn chart_mut(&mut self) -> &mut dyn DynChart {
        &mut *self.chart
    }

    /// Replace the inner chart with a new one, marking the widget dirty.
    pub fn set_chart(&mut self, chart: impl DynChart) {
        self.chart = Box::new(chart);
        self.dirty = true;
    }

    /// Drain and return all interaction events translated during the last
    /// frame.
    ///
    /// Returns events that were generated by translating egui pointer events
    /// into Gup [`InteractionEvent`](gup::interaction::InteractionEvent)
    /// types. The vector is cleared after calling this method.
    pub fn take_events(&mut self) -> Vec<gup::interaction::InteractionEvent> {
        std::mem::take(&mut self.pending_events)
    }

    /// Render the widget inside the given egui [`Ui`](egui::Ui).
    ///
    /// This is the main entry point. It:
    /// 1. Determines the available size in the panel.
    /// 2. Re-renders the chart if dirty or the size changed.
    /// 3. Displays the chart texture via [`egui::Image`].
    /// 4. Translates pointer events from the [`egui::Response`].
    pub fn show(&mut self, ui: &mut egui::Ui) -> egui::Response {
        // Clear pending events from the previous frame.
        self.pending_events.clear();

        // Determine the available size in logical points.
        let available = ui.available_size();
        let ppp = ui.ctx().pixels_per_point();

        // Convert to physical pixels for GPU rendering.
        let phys_width = (available.x * ppp).round().max(1.0) as u32;
        let phys_height = (available.y * ppp).round().max(1.0) as u32;

        // Check if the size changed.
        let size_changed = self
            .last_size
            .map_or(true, |s| s[0] != phys_width || s[1] != phys_height);

        // Re-render if dirty or size changed.
        if self.dirty || size_changed {
            self.rerender(ui, phys_width, phys_height);
            self.last_size = Some([phys_width, phys_height]);
            self.dirty = false;
        }

        // Display the texture (or a placeholder).
        let size = egui::vec2(available.x, available.y);
        let response = if let Some(handle) = &self.texture_handle {
            let image = egui::Image::new(handle).fit_to_exact_size(size);
            ui.add(image)
        } else {
            // No texture yet — draw a placeholder rectangle.
            let (rect, response) = ui.allocate_exact_size(size, egui::Sense::click_and_drag());
            ui.painter()
                .rect_filled(rect, 0.0, egui::Color32::from_gray(240));
            response
        };

        // Translate egui pointer events into Gup interaction events.
        let chart_rect = response.rect;
        let events = bridge::translate_response(&response, chart_rect, ppp);
        self.pending_events = events;

        response
    }

    /// Perform the off-screen render and upload the result to egui.
    fn rerender(&mut self, ui: &mut egui::Ui, width: u32, height: u32) {
        // Render the chart to PNG bytes.
        let png_bytes = match self.chart.render_to_png(width, height) {
            Ok(bytes) => bytes,
            Err(e) => {
                log::warn!("GupWidget render failed: {e}");
                return;
            }
        };

        // Decode the PNG into RGBA pixels.
        let decoded = match image::load_from_memory_with_format(&png_bytes, image::ImageFormat::Png)
        {
            Ok(img) => img.to_rgba8(),
            Err(e) => {
                log::warn!("Failed to decode chart PNG: {e}");
                return;
            }
        };

        let (w, h) = decoded.dimensions();
        let pixels = decoded.into_raw();

        // Build an egui ColorImage from the pixel data.
        let color_image = ColorImage::from_rgba_unmultiplied([w as usize, h as usize], &pixels);

        // Upload (or replace) the egui texture.
        match &mut self.texture_handle {
            Some(handle) => {
                handle.set(color_image, TextureOptions::LINEAR);
            }
            None => {
                let handle =
                    ui.ctx()
                        .load_texture("gup_chart", color_image, TextureOptions::LINEAR);
                self.texture_handle = Some(handle);
            }
        }
    }
}

/// Implement [`egui::Widget`] for `&mut GupWidget` so it can be passed to
/// [`Ui::add`](egui::Ui::add).
///
/// ```rust,ignore
/// ui.add(&mut my_widget);
/// ```
impl egui::Widget for &mut GupWidget {
    fn ui(self, ui: &mut egui::Ui) -> egui::Response {
        self.show(ui)
    }
}
